### ISSUE TITLE
Does calendgraph has license policy?

### ISSUE THREAD

**Issue by tosaoi0711** [tcampb/calendgraph#1]
Hi @tcampb, I'm not quite sure if here is a right path to throw this kind of question but I'd like to know if the calendgraph has any licence policy such as MIT,  BSD  and etc. Since I'd like to use the code in my project to query Calendly API via GraphQL and need to check if commercial use is permitted or not. Thanks!

**Comment by tcampb** [comment]
Hey @tosaoi0711, just added an MIT license :tada:!

https://github.com/tcampb/calendgraph/blob/main/LICENSE.md

**Comment by tosaoi0711** [comment]
@tcampb Thanks a lot!!

**Comment by tosaoi0711** [comment]
My quiestion is fully answered so let me close this issue.
